version: '3.8'

services:
    web:
      build:
        context: .
        dockerfile: prod.Dockerfile
      command: gunicorn petstagram.wsgi:application --bind 0.0.0.0:8000
      volumes:
          - static_volume:/home/app/web/staticfiles
      expose:
        - 8000
      env_file:
        - envs/.env.prod
      depends_on:
        - db

    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - envs/.env.secure.db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
        ports:
            - '80:80'
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
