# Generated by Django 3.2.12 on 2023-04-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(blank=True, default='images/accounts/default/default_account_image.png', upload_to='images/accounts'),
        ),
    ]
